#ifndef FT_VOX_NOISEUTILS_HPP
#define FT_VOX_NOISEUTILS_HPP

#include <array>

#include "glm/glm.hpp"

#include "PerlinNoise.hpp"

template<typename Iterator, typename T>
constexpr T
sum_array(Iterator begin, Iterator end, T init_val)
{
    for (; begin != end; ++begin) {
        init_val = std::move(init_val) + *begin;
    }
    return (init_val);
}

constexpr std::array<float, 4> const OCTAVE_COEFF = { 0.8f,
                                                      0.65f,
                                                      1.00f,
                                                      0.65f };
constexpr float const OCTAVE_COEFF_SUM =
  sum_array(OCTAVE_COEFF.begin(), OCTAVE_COEFF.end(), 0.0f);

[[nodiscard]] float generateValueWithOctave(glm::vec2 const &coord,
                                            PerlinNoise const &pn);
void generateMap(glm::ivec2 const &size, uint32_t seed, void *buffer);
/** \brief Helper to remap value generated by 3D perlin noise
 * \param A 3D vector
 * \param A perlin noise generator
 * \return value between [0; 1]
 */
[[nodiscard]] float noise3dRemapped(glm::vec3 const &vec, PerlinNoise const &pn);
/** \brief Helper to remap value generated by 2D perlin noise
 * \param A 2D vector
 * \param A perlin noise generator
 * \return value between [0; 1]
 */
[[nodiscard]] float noise2dRemapped(glm::vec2 const &vec, PerlinNoise const &pn);

#endif // FT_VOX_NOISEUTILS_HPP